### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by brobits** [graphsense/graphsense-blocksci#2]
This project does not build using the dockerfile:

```bash
 running build_ext
    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.7")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- pybind11 v2.2.4
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /opt/BlockSci/blockscipy/build/temp.linux-x86_64-3.6
    Scanning dependencies of target _blocksci
    [  1%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy/proxy_functions_core.cpp.o
    [  2%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy/proxy_flow_functions_scripts.cpp.o
    [  3%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy/proxy_flow_functions_core.cpp.o
    [  4%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy/proxy_flow_functions_other.cpp.o
    [  6%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy/proxy_functions_other.cpp.o
    [  7%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy/proxy_functions_scripts.cpp.o
    [  8%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/block/block_proxy_py.cpp.o
    [  9%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/block/block_py.cpp.o
    [ 10%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/blockchain_py.cpp.o
    [ 12%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/input/input_proxy_py.cpp.o
    [ 13%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/input/input_py.cpp.o
    [ 14%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/output/output_proxy_py.cpp.o
    [ 15%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/output/output_py.cpp.o
    [ 16%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/tx/tx_proxy_py.cpp.o
    [ 18%] Building CXX object CMakeFiles/_blocksci.dir/src/chain/tx/tx_py.cpp.o
    [ 19%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_proxy_py.cpp.o
    [ 20%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_py.cpp.o
    [ 21%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/tagged_address/tagged_address_proxy_py.cpp.o
    [ 22%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/tagged_address/tagged_address_py.cpp.o
    [ 24%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/tagged_cluster/tagged_cluster_proxy_py.cpp.o
    [ 25%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/tagged_cluster/tagged_cluster_py.cpp.o
    [ 26%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/address_proxy_py.cpp.o
    [ 27%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/address_py.cpp.o
    [ 28%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/equiv_address/equiv_address_proxy_py.cpp.o
    [ 30%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/equiv_address/equiv_address_py.cpp.o
    [ 31%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/multisig/multisig_proxy_py.cpp.o
    [ 32%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/multisig/multisig_py.cpp.o
    [ 33%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/nonstandard/nonstandard_proxy_py.cpp.o
    [ 34%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/nonstandard/nonstandard_py.cpp.o
    [ 36%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/nulldata/nulldata_proxy_py.cpp.o
    [ 37%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/nulldata/nulldata_py.cpp.o
    [ 38%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/pubkey/multisig_pubkey/multisig_pubkey_proxy_py.cpp.o
    [ 39%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/pubkey/pubkey/pubkey_proxy_py.cpp.o
    [ 40%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/pubkey/pubkey_py.cpp.o
    [ 42%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/pubkey/pubkeyhash/pubkeyhash_proxy_py.cpp.o
    [ 43%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/pubkey/witness_pubkeyhash/witness_pubkeyhash_proxy_py.cpp.o
    [ 44%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/scripthash/scripthash/scripthash_proxy_py.cpp.o
    [ 45%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/scripthash/scripthash_py.cpp.o
    [ 46%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/scripthash/witness_scripthash/witness_scripthash_proxy_py.cpp.o
    [ 48%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/witness_unknown/witness_unknown_proxy_py.cpp.o
    [ 49%] Building CXX object CMakeFiles/_blocksci.dir/src/scripts/witness_unknown/witness_unknown_py.cpp.o
    [ 50%] Building CXX object CMakeFiles/_blocksci.dir/src/blocksci_iterator_type.cpp.o
    [ 51%] Building CXX object CMakeFiles/_blocksci.dir/src/blocksci_range_type.cpp.o
    [ 53%] Building CXX object CMakeFiles/_blocksci.dir/src/blocksci_type.cpp.o
    [ 54%] Building CXX object CMakeFiles/_blocksci.dir/src/blocksci_type_converter.cpp.o
    [ 55%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy.cpp.o
    [ 56%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_sequence.cpp.o
    [ 57%] Building CXX object CMakeFiles/_blocksci.dir/src/heuristics_py.cpp.o
    [ 59%] Building CXX object CMakeFiles/_blocksci.dir/src/method_types.cpp.o
    [ 60%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy_create.cpp.o
    [ 61%] Building CXX object CMakeFiles/_blocksci.dir/src/proxy_type_check.cpp.o
    [ 62%] Building CXX object CMakeFiles/_blocksci.dir/src/python_interface.cpp.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    CMakeFiles/_blocksci.dir/build.make:1046: recipe for target 'CMakeFiles/_blocksci.dir/src/blocksci_iterator_type.cpp.o' failed
    make[2]: *** [CMakeFiles/_blocksci.dir/src/blocksci_iterator_type.cpp.o] Error 4
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/_blocksci.dir/all' failed
    make[1]: *** [CMakeFiles/_blocksci.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/BlockSci/blockscipy/setup.py", line 77, in <module>
        'requests>=2.19.1'
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/BlockSci/blockscipy/setup.py", line 32, in run
        self.build_extension(ext)
      File "/opt/BlockSci/blockscipy/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/BlockSci/blockscipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/BlockSci/blockscipy/
The command '/bin/sh -c cd /opt &&     git clone https://github.com/citp/BlockSci.git &&     cd BlockSci &&     git checkout "v0.6" &&     git submodule init &&     git submodule update --recursive &&     mkdir release &&     cd release &&     cmake -DCMAKE_BUILD_TYPE=Release .. &&     make &&     make install &&     cd /opt/BlockSci &&     pip3 install requests &&     pip3 install cassandra-driver==3.16.0 &&     pip3 install -e blockscipy &&     cd / &&     mv /opt/BlockSci/blockscipy /opt/ &&     rm -rf /opt/BlockSci/* &&     mv /opt/blockscipy /opt/BlockSci &&     rm -rf /opt/BlockSci/blockscipy/build /root/.cache &&     apt-get autoremove -y --purge             autoconf             automake             build-essential             git             libboost-atomic1.62-dev             libboost-chrono1.62-dev             libboost-date-time1.62-dev             libboost-filesystem1.62-dev             libboost-iostreams1.62-dev             libboost-program-options1.62-dev             libboost-regex1.62-dev             libboost-system1.62-dev             libboost-serialization1.62-dev             libboost-thread1.62-dev             libjsoncpp-dev             libjsonrpccpp-dev             libjsonrpccpp-tools             libssl-dev             libsparsehash-dev             libtool &&     mkdir -p /var/data/blocksci_data &&     mkdir -p /var/data/block_data &&     chown -R dockeruser /var/data/' returned a non-zero code: 1
```

I am using GCC 7.3 and python 3.6.7 and this still does not build. I have tried solutions in this issue to no avail https://github.com/citp/BlockSci/issues/106

If there's something simple I am missing, or I'm making an obvious mistake, please let me know. Thanks!

**Comment by defconst** [comment]
Sorry, I can't reproduce the problem (docker-ce 18.09):

```
...
Removing intermediate container 55a25e06b00f
 ---> cdd081ad5327
Step 4/6 : COPY blocksci_export.py /usr/local/bin/blocksci_export.py
 ---> 2c80818e1911
Step 5/6 : USER dockeruser
 ---> Running in 7c7c94ba89a9
Removing intermediate container 7c7c94ba89a9
 ---> ea25b637ba0f
Step 6/6 : WORKDIR /home/dockeruser
 ---> Running in d4c8c6bc86a4
Removing intermediate container d4c8c6bc86a4
 ---> 4a842f50fc18
Successfully built 4a842f50fc18
Successfully tagged blocksci-dev:latest
```

**Comment by brobits** [comment]
Ah I was using docker EE 1.x on a CentOS system and the container was not building.  my mistake, thanks for letting me know about your docker version & checking in on my issue
