### ISSUE TITLE
How to define Cassandra Port?

### ISSUE THREAD

**Issue by modir** [graphsense/graphsense-blocksci#25]
In the .env file I can set the IP address of the cassandra seed server but not it's port. Now when I start the ingest-btc appliaction it can not connect to cassandra as it is using the wrong port. cassandra is on port 7077 and not 9042.

```
[root@graphsense-master ingest]# docker-compose run ingest-btc
WARNING: The GETH_IPC variable is not set. Defaulting to a blank string.
Creating ingest_ingest-btc_run ... done
Creating Cassandra keyspace btc_raw
Traceback (most recent call last):
  File "/usr/local/bin/create_keyspace.py", line 38, in connect
    self.session = self.cluster.connect()
  File "cassandra/cluster.py", line 1667, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1703, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1690, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3488, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3533, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'192.168.66.188:9042': OSError(113, "Tried connecting to [('192.168.66.188', 9042)]. Last error: No route to host")})
```
How can I change the port?

**Comment by defconst** [comment]
Added `--db_port` argument in edcbfdb
