### ISSUE TITLE
Error exporting

### ISSUE THREAD

**Issue by luisalrp** [graphsense/graphsense-blocksci#7]
Hello,

I get this error and I am not really sure why and how to fix it.

dockeruser@7049af82e1b4:~$ blocksci_export.py -c /var/data/blocksci_data/btc.cfg -d 172.19.0.3 -k graphsense --start_index 0
Traceback (most recent call last):
  File "/usr/local/bin/blocksci_export.py", line 437, in <module>
    main()
  File "/usr/local/bin/blocksci_export.py", line 355, in main
    (chain[-1].height, datetime.strftime(chain[-1].time, '%F %T')))
IndexError

**Comment by luisalrp** [comment]
It was a problem about having a bad/partially parsed blockchain by blocksci.
