### ISSUE TITLE
Error importing blocksci 0.6 data to cassandra

### ISSUE THREAD

**Issue by mayankpunetha007** [graphsense/graphsense-blocksci#8]
$ sudo python3 ~/Develop/graphsense-blocksci/scripts/blocksci_export.py -c ~/.blocksci -d 127.0.0.1 -k graphsense  
Last parsed block: 631525 (2020-05-24 19:45:12)
Transactions (532,655,010 tx)
tx index: 0 -- 532,655,009
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 99, in insert
    param_list.append(tx_summary(tx))
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 282, in tx_summary
    tx_outputs = [tx_io_summary(x) for x in tx.outputs]
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 282, in <listcomp>
    tx_outputs = [tx_io_summary(x) for x in tx.outputs]
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 277, in tx_io_summary
    return [addr_str(x.address), x.value, address_type[repr(x.address_type)]]
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 254, in addr_str
    elif addr_obj.type == blocksci.address_type.witness_unknown:
AttributeError: type object 'blocksci.address_type' has no attribute 'witness_unknown'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 437, in <module>
    main()
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 404, in main
    qm.execute(TxQueryManager.insert, tx_index_range)
  File "/home/mpunetha/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 39, in wrap
    result = f(*args, **kw)
  File "~/Develop/graphsense-blocksci/scripts/blocksci_export.py", line 76, in execute
    self.pool.map(fun, chunk(params, self.num_chunks))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: type object 'blocksci.address_type' has no attribute 'witness_unknown'

I get the above exception, Is this something known with the blocksci 0,6?

**Comment by luisalrp** [comment]
I got the following error while exporting data from blocksci to cassandra. I think this error is because I run out of RAM.

Last parsed block: 630677 (2020-05-17 06:15:35)
Transactions (530,719,008 tx)
tx index: 0 -- 530,719,007
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/usr/local/lib/python3.6/dist-packages/cassandra/__init__.py", line 490, in __init__
    Timeout.__init__(self, message, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cassandra/__init__.py", line 441, in __init__
    kwargs["write_type"] = WriteType.value_to_name[kwargs["write_type"]]
KeyError: None

**Comment by rubujubi** [comment]
> I got the following error while exporting data from blocksci to cassandra. I think this error is because I run out of RAM.
> 
> Last parsed block: 630677 (2020-05-17 06:15:35)
> Transactions (530,719,008 tx)
> tx index: 0 -- 530,719,007
> Exception in thread Thread-3:
> Traceback (most recent call last):
> File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> self.run()
> File "/usr/lib/python3.6/threading.py", line 864, in run
> self._target(*self._args, **self._kwargs)
> File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
> task = get()
> File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
> return _ForkingPickler.loads(buf.getbuffer())
> File "/usr/local/lib/python3.6/dist-packages/cassandra/**init**.py", line 490, in **init**
> Timeout.**init**(self, message, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/cassandra/**init**.py", line 441, in **init**
> kwargs["write_type"] = WriteType.value_to_name[kwargs["write_type"]]
> KeyError: None

Can you give some information about your RAM? Thanks.

**Comment by defconst** [comment]
`address_type.witness_unknown` was added in d0b91cce (0.4.2)
